#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_main_controller:
  path: /
  controller: App\Controller\MainController::main

app_main_list:
  path: /list/{id}
  controller: App\Controller\MainController::list
  methods: GET|HEAD


app_product_show:
  path: /product/{id}
  controller: App\Controller\ProductController::showProduct

app_product_push:
  path: /product
  methods: POST
  controller: App\Controller\MainController::adProduct

app_product_create:
  path: /productcrt
  controller: App\Controller\MainController::addProduct

app_product_delete:

    path: /product/delete/{id}
    controller: App\Controller\ProductController::deleteProduct

app_login_login:
  path: /login
  controller: App\Controller\MainController::login

app_login_register:
  path: /register
  controller: App\Controller\MainController::register

app_user_show:
  path: /user/{id}
  controller: App\Controller\UserController::show
app_user_tryregister:
  path: /user/register
  controller: App\Controller\UserController::tryRegister
