#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
  path: /lucky
  controller: App\Controller\LuckyController::number
app_main_controller:
  path: /
  controller: App\Controller\MainController::main
