#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_main_controller:
  path: /
  controller: App\Controller\MainController::main

app_main_list:
  path: /list/{id}
  controller: App\Controller\MainController::list
  methods: GET|HEAD


app_product_view:
  path: /product/{id}
  controller: App\Controller\MainController::productView

app_product_edit:
  path: /product/edit/{id}
  controller: App\Controller\MainController::productEdit
app_product_performedit:
  path: /produtct/edit/
  methods: POST
  controller: App\Controller\MainController::productEditPerform

app_product_pushbasket:
  path: /product/basket/{id}
  methods: POST
  controller: App\Controller\MainController::productBuy

app_product_push:
  path: /product
  methods: POST
  controller: App\Controller\MainController::adProduct

app_product_create:
  path: /productcrt
  controller: App\Controller\MainController::addProduct

app_product_delete:

    path: /product/delete/{id}
    controller: App\Controller\ProductController::deleteProduct

app_login_login:
  path: /login
  controller: App\Controller\MainController::login

app_login_register:
  path: /register
  controller: App\Controller\MainController::register

app_login_tryregisterWorker:
  path: /register/worker
  controller: App\Controller\UserController::tryWorkerRegister

app_user_tryregister:
  path: /user/register
  controller: App\Controller\UserController::tryRegister
  methods: POST

app_info:
  path: /info
  controller: App\Controller\MainController::info

app_basket_show:
  path: /basket
  controller: App\Controller\MainController::basketShow

app_basket_drop:
  path: /basket/drop
  controller: App\Controller\MainController::basketDrop

app_basket_delete:
  path: /basket/delete/{id}
  controller: App\Controller\MainController::basketDelete

app_basket_change:
  path: /basket/change
  controller: App\Controller\MainController::basketChange

app_basket_order:
  path: /basket/order
  controller: App\Controller\MainController::basketOrder

app_basket_tryorder:
  path: /basket/order/try
  controller: App\Controller\MainController::basketTryOrder

app_admin_order:
  path: /admin/order
  controller: App\Controller\MainController::adminOrders

app_admin_users:
  path: /admin/users
  controller: App\Controller\MainController::adminUsers

app_admin_userdetails:
  path: /admin/users/details
  controller: App\Controller\MainController::adminUserDetails

app_admin_workers:
  path: /admin/workers
  controller: App\Controller\AdminController::workersList



app_forgotpass:
  path: /forgotpass
  controller: App\Controller\MainController::forgotpass

app_login_try:
  path: /login/try
  controller: App\Controller\UserController::tryLogin
  methods: POST

app_login_out:
  path: /login/out
  controller: App\Controller\UserController:loginOut
